#!/bin/bash

# some more file manipulation aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias lt='ll -t'
alias du='du -sh'
alias rm='rm -i'

function cd() {
    new_directory="$*";
    if [ $# -eq 0 ]; then
        new_directory=${HOME};
    fi;
    builtin cd "${new_directory}" && ls -a
}

alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."

# vim
alias vi='nvim'

# git aliases and tools
git config --global alias.st 'status -sb'
git config --global alias.last 'log -1 HEAD --stat'
git config --global alias.cm 'commit -m'
git config --global alias.rv 'remote -v'
git config --global alias.diffvim 'difftool -t vimdiff -y'
git config --global alias.update 'add --update'

# htvs aliases
alias shellplus='$DJANGOCHEMDIR/manage.py shell_plus --settings=djangochem.settings.orgel'

# engaging aliases
alias ssh_eofe="ssh -F $HOME/.ssh/eofe-cluster/linux/config eofe8.mit.edu"
alias mcl="sshfs atan14@eofe8.mit.edu:/home/atan14/ ~/mnt/cluster -F /home/atan14/.ssh/eofe-cluster/linux/config"
alias mstorage="sshfs atan14@eofe8.mit.edu:/nfs/pool002/users/atan14/ ~/mnt/storage -F /home/atan14/.ssh/eofe-cluster/linux/config"
alias mcl_reconnect="sshfs -o reconnect atan14@eofe8.mit.edu: ~/mnt/cluster -F /home/atan14/.ssh/eofe-cluster/linux/config"
alias mstorage_reconnect="sshfs -o reconnect atan14@eofe8.mit.edu:/nfs/pool002/users/atan14/ ~/mnt/storage -F /home/atan14/.ssh/eofe-cluster/linux/config"

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
