#!/bin/bash

# some more file manipulation aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias lt='ll -t'
alias du='du -sh'
alias rm='rm -i'

function cd() {
    new_directory="$*";
    if [ $# -eq 0 ]; then
        new_directory=${HOME};
    fi;
    builtin cd "${new_directory}" && ls -a
}

alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."

# htvs aliases
alias shellplus='$DJANGOCHEMDIR/manage.py shell_plus --settings=djangochem.settings.orgel'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
