#!/bin/bash

export EDITOR="vim"

export PROJECTSDIR="$HOME/projects"
export AGCDIR="$PROJECTSDIR/AGC"
export HTVSDIR="$PROJECTSDIR/htvs"
export DJANGOCHEMDIR="$HTVSDIR/djangochem"
export NFFDIR="$PROJECTSDIR/NeuralForceField"
export EVIDIR="$PROJECTSDIR/evidential"
export ADVATTACKDIR="$PROJECTSDIR/Atomistic-Adversarial-Attacks"
export PERSONALPYTHONFILE="$PROJECTSDIR/personal_utils/"
export PYTHONPATH=$HTVSDIR:$DJANGOCHEMDIR:$PROJECTSDIR:$NFFDIR:$ADVATTACKDIR:$EVIDIR:$PERSONALPYTHONFILE:$CLASSDIR:$PYTHONPATH

# fzf exports
export FZF_DEFAULT_COMMAND="rg --files --ignore-case -g '!*.log'"
export FZF_DEFAULT_OPTS="-m --height 40% --layout=reverse --border --inline-info --preview 'bat --style=numbers --color=always --line-range :500 {}'"
export FZF_COMPLETION_OPTS='--border --info=inline'
# To apply the command to CTRL-T as well
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
