#!/bin/bash

# some more file manipulation aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias lt='ll -tr'
alias du='du -sh'
alias rm='rm -i'

function cd() {
    new_directory="$*";
    if [ $# -eq 0 ]; then
        new_directory=${HOME};
    fi;
    builtin cd "${new_directory}" && ls -a
}

# vim commands
alias vio='vi -o'
alias vimdiff='vi -d'

# Create aliases that go back as many dots as desired
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias ......="cd ../../../../.."
alias .......="cd ../../../../../.."
alias ........="cd ../../../../../../.."
alias .........="cd ../../../../../../../.."
alias ..........="cd ../../../../../../../../.."


function catf() {
    for file in "$@"
    do
        echo "=== $file ==="
        cat "$file"
    done
}


pid() {
    ps -p $1 -o pid,vsz=MEMORY -o user,group=GROUP -o comm,args=ARGS
}

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
